### ISSUE TITLE
Add General Error and Success States

### ISSUE THREAD

**Issue by jaxgeller** [jaxgeller/open-ipsum-ui#3]
Needs some kind of success and error messages, notifications, underlines, modals, etc…

Like what happens when you sign in, create an ipsum, or copy text to the clipboard?

**Comment by jhil** [comment]
over to you @jaxgeller :point_right:

**Comment by jhil** [comment]
zpl.io/Z2bFgvI
zpl.io/ZKyvXJ
zpl.io/Z1TGLcn
zpl.io/179bu8
