### ISSUE TITLE
Add About Page

### ISSUE THREAD

**Issue by jaxgeller** [jaxgeller/open-ipsum-ui#31]
Who we are, where we been, what we are doing. 

Just kidding, maybe just twitter profiles or something.

**Comment by jaxgeller** [comment]
Also like to mention the 

+ API for using OI
+ Links for social media
+ Links for how to integrate the setup in your tools, like Illustrator.

**Comment by jhil** [comment]
"When we set out six months ago to create Open Ipsum, we had a vision to bring ipsums to the people and democratize placeholders for our generation of creators..."
