### ISSUE TITLE
About and 404 ipsum should appear on homepage

### ISSUE THREAD

**Issue by jhil** [jaxgeller/open-ipsum-ui#44]

**Comment by jaxgeller** [comment]
@jhil Easy fix, actually wrote some code to make sure they didn't.

**Comment by jhil** [comment]
What was your reasoning? I could be convinced.

**Comment by jaxgeller** [comment]
I thought it was more of an easter egg, rather than an actual ipsum you'd like to use.

**Comment by jhil** [comment]
sure. i dont really care one way or another.
