### ISSUE TITLE
Set non-queried ipsum blocks to .5 opacity during active search

### ISSUE THREAD

**Issue by jhil** [jaxgeller/open-ipsum-ui#45]

**Comment by jaxgeller** [comment]
<img width="1278" alt="screen shot 2015-12-25 at 2 24 58 pm" src="https://cloud.githubusercontent.com/assets/4494509/12004198/735ea9de-ab13-11e5-856a-c16de5f009f3.png">

@jhil Blue or red

**Comment by jhil** [comment]
lets make red a lower opacity, to provide emphasis on the search results
